/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Connection.ConnectionFactory;
import Model.bean.Cliente;
import Model.bean.OS;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.List;
import Model.dao.ClienteDAO;
import Model.dao.OsDAO;




/**
 *
 * @author teonilia
 */
public class TelaPrincipal extends javax.swing.JFrame {

    
     /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {       
        initComponents();
       
        
        
     
            
    }

   
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menCad = new javax.swing.JMenu();
        menCli = new javax.swing.JMenuItem();
        menServ = new javax.swing.JMenuItem();
        menUser = new javax.swing.JMenuItem();
        menRel = new javax.swing.JMenu();
        jRadioButtonMenuItem3 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem4 = new javax.swing.JRadioButtonMenuItem();
        MenAju = new javax.swing.JMenu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        MenOpc = new javax.swing.JMenu();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Technical Assistance");

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setToolTipText("");
        jPanel1.setName(""); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/technical-support-2_icon-icons.com_52811.png"))); // NOI18N
        jLabel1.setName(""); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(155, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(155, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menCad.setBorder(null);
        menCad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/User-80_icon-icons.com_57249.png"))); // NOI18N
        menCad.setText("Cadastro");

        menCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/User_Group-80_icon-icons.com_57247.png"))); // NOI18N
        menCli.setText("Clientes");
        menCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCliActionPerformed(evt);
            }
        });
        menCad.add(menCli);

        menServ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/business_table_order_report_history_2332.png"))); // NOI18N
        menServ.setText("OS");
        menServ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menServActionPerformed(evt);
            }
        });
        menCad.add(menServ);

        menUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Add_User-80_icon-icons.com_57380.png"))); // NOI18N
        menUser.setText("Usuários");
        menUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menUserActionPerformed(evt);
            }
        });
        menCad.add(menUser);

        jMenuBar1.add(menCad);

        menRel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Sales-report_25411.png"))); // NOI18N
        menRel.setText("Relatório");
        menRel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menRelActionPerformed(evt);
            }
        });

        jRadioButtonMenuItem3.setSelected(true);
        jRadioButtonMenuItem3.setText("Clientes");
        jRadioButtonMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8-arquivo-48.png"))); // NOI18N
        jRadioButtonMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem3ActionPerformed(evt);
            }
        });
        menRel.add(jRadioButtonMenuItem3);

        jRadioButtonMenuItem4.setSelected(true);
        jRadioButtonMenuItem4.setText("Ordem de Serviço");
        jRadioButtonMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8-arquivo-48 (1).png"))); // NOI18N
        jRadioButtonMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem4ActionPerformed(evt);
            }
        });
        menRel.add(jRadioButtonMenuItem4);

        jMenuBar1.add(menRel);

        MenAju.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Help_icon-icons.com_73700.png"))); // NOI18N
        MenAju.setText("Ajuda");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("Sobre");
        jRadioButtonMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/about_3697.png"))); // NOI18N
        jRadioButtonMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem1ActionPerformed(evt);
            }
        });
        MenAju.add(jRadioButtonMenuItem1);

        jMenuBar1.add(MenAju);

        MenOpc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/construction_project_plan_building_architect_design_develop-57_icon-icons.com_60216.png"))); // NOI18N
        MenOpc.setText("Opções");
        MenOpc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenOpcActionPerformed(evt);
            }
        });

        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("Sair");
        jRadioButtonMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Logout_37127.png"))); // NOI18N
        jRadioButtonMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem2ActionPerformed(evt);
            }
        });
        MenOpc.add(jRadioButtonMenuItem2);

        jMenuBar1.add(MenOpc);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.getAccessibleContext().setAccessibleName("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menUserActionPerformed
       TelaUsuario usuario = new TelaUsuario();
       new TelaUsuario().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_menUserActionPerformed

    private void menCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCliActionPerformed
        TelaCliente cliente = new TelaCliente();
        new TelaCliente().setVisible(true);
         this.dispose();
    }//GEN-LAST:event_menCliActionPerformed

    private void menServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menServActionPerformed
        TelaOS os = new TelaOS();
        new TelaOS().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_menServActionPerformed

    private void jRadioButtonMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem1ActionPerformed
       TelaSobre sobre = new TelaSobre();
       new TelaSobre().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jRadioButtonMenuItem1ActionPerformed

    private void MenOpcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenOpcActionPerformed
    }//GEN-LAST:event_MenOpcActionPerformed

    private void jRadioButtonMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem2ActionPerformed
       TelaLogin login = new TelaLogin();
       new TelaLogin().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jRadioButtonMenuItem2ActionPerformed

    private void jRadioButtonMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem3ActionPerformed
     
        ClienteDAO dao = new ClienteDAO();
         
        Document document = new Document();
        
        List<Cliente> lista = dao.read();
        String arquivoPDF = "relatorio de clientes.pdf";
        
        try {
            PdfWriter.getInstance(document, new FileOutputStream(arquivoPDF));
            document.open();
            
            Paragraph p = new Paragraph("Relatório");
            
            p.setAlignment(1);
            document.add(p);
            p = new Paragraph("  ");
            document.add(p);
            
            PdfPTable table = new PdfPTable(4);
            
            PdfPCell cel1 = new PdfPCell(new Paragraph("Nome"));
            PdfPCell cel2 = new PdfPCell(new Paragraph("Endereço"));
            PdfPCell cel3 = new PdfPCell(new Paragraph("CPF"));
            PdfPCell cel4 = new PdfPCell(new Paragraph("E-mail"));
            
            table.addCell(cel1);
            table.addCell(cel2);
            table.addCell(cel3);
            table.addCell(cel4);
            
            
            for(Cliente cliente : lista){
            cel1 = new PdfPCell(new Paragraph(cliente.getNomecli()));
            cel2 = new PdfPCell(new Paragraph(cliente.getEndcli()));
            cel3 = new PdfPCell(new Paragraph(cliente.getCpf()));
            cel4 = new PdfPCell(new Paragraph(cliente.getEmailcli()));
                
            table.addCell(cel1);
            table.addCell(cel2);
            table.addCell(cel3);
            table.addCell(cel4);
           
            
       }
            document.add(table);
            document.close();
            Desktop.getDesktop().open(new File(arquivoPDF));
            
        } catch (DocumentException | FileNotFoundException ex) {
           System.out.println("Erro" +ex);
        } catch (IOException ex) {
           System.out.println("Erro" +ex);
        } 
        

    }//GEN-LAST:event_jRadioButtonMenuItem3ActionPerformed

    private void menRelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menRelActionPerformed
        
    }//GEN-LAST:event_menRelActionPerformed

    private void jRadioButtonMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem4ActionPerformed
        OsDAO dao = new OsDAO();
         
        Document document = new Document();
        
        List<OS> lista = dao.read();
        String arquivoPDF = "relatorio de serviços.pdf";
        
        try {
            PdfWriter.getInstance(document, new FileOutputStream(arquivoPDF));
            document.open();
            
            Paragraph p = new Paragraph("Relatório");
            
            p.setAlignment(1);
            document.add(p);
            p = new Paragraph("  ");
            document.add(p);
            
            PdfPTable table = new PdfPTable(7);
            
           
            PdfPCell cel1 = new PdfPCell(new Paragraph("Tipo"));
            PdfPCell cel2 = new PdfPCell(new Paragraph("Situação"));
            PdfPCell cel3 = new PdfPCell(new Paragraph("Equipamento"));
            PdfPCell cel4 = new PdfPCell(new Paragraph("Defeito"));
            PdfPCell cel5 = new PdfPCell(new Paragraph("Serviço"));
            PdfPCell cel6 = new PdfPCell(new Paragraph("Técnico"));     
            PdfPCell cel7 = new PdfPCell(new Paragraph("Cliente"));
            
            table.addCell(cel1);
            table.addCell(cel2);
            table.addCell(cel3);
            table.addCell(cel4);
            table.addCell(cel5);
            table.addCell(cel6);
            table.addCell(cel7);
           
            
            
            for(OS os : lista){
            
            cel1 = new PdfPCell(new Paragraph(os.getTipo()));
            cel2 = new PdfPCell(new Paragraph(os.getSituacao()));
            cel3 = new PdfPCell(new Paragraph(os.getEquipamento()));
            cel4 = new PdfPCell(new Paragraph(os.getDefeito()));
            cel5 = new PdfPCell(new Paragraph(os.getServico()));
            cel6 = new PdfPCell(new Paragraph(os.getTecnico()));         
            cel7 = new PdfPCell(new Paragraph(os.getNomecli()));
                
            table.addCell(cel1);
            table.addCell(cel2);
            table.addCell(cel3);
            table.addCell(cel4);
            table.addCell(cel5);
            table.addCell(cel6);
            table.addCell(cel7);
           
           
            
       }
            document.add(table);
            document.close();
            Desktop.getDesktop().open(new File(arquivoPDF));
            
        } catch (DocumentException | FileNotFoundException ex) {
           System.out.println("Erro" +ex);
        } catch (IOException ex) {
           System.out.println("Erro" +ex);
        } 
    }//GEN-LAST:event_jRadioButtonMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenAju;
    private javax.swing.JMenu MenOpc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem3;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem4;
    private javax.swing.JMenu menCad;
    private javax.swing.JMenuItem menCli;
    public static javax.swing.JMenu menRel;
    public static javax.swing.JMenuItem menServ;
    public static javax.swing.JMenuItem menUser;
    // End of variables declaration//GEN-END:variables
}
